### ISSUE TITLE
Setting 100% width on the Vega container by default?

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/dash-vega-components#11]
Thanks for this great dash extension @binste ! It's saving me from so many iframe headaches =)

I wonder if it would make sense to set `style={'width': '100%'}` by default on the `Vega` component, so that there is only one step required to make the altair chart stretch the width of the container. Or is there any advantage of not having this by default?

One step further would be to provide a "dash-style" altair theme that sets `width='container'` for all charts when activated.

**Comment by binste** [comment]
Thanks for the feedback @joelostblom !

Yeah I was just never sure how to do this properly so that users can still set it themselves and that it does not interfere with other style properties. I know found a way in #12. Just released it as version 0.10.0. Probably not the most elegant solution but I tested it in a few different cases and seems to work well. Let me know if you face any issues!

**Comment by joelostblom** [comment]
Thank you @binste !
